apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: production
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: 500m
        memory: 512Mi
