---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: k8s-ai-monitor
  namespace: observability
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-image-automation
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-image-automation@users.noreply.github.com
        name: Flux Image Automation
      messageTemplate: |
        Update k8s-ai-monitor image

        [ci skip]
    push:
      branch: main
  update:
    path: ./flux/infrastructure/observability/k8s-ai-monitor
    strategy: Setters
