apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: production
type: Opaque
stringData:
    uptrace-dsn: ENC[AES256_GCM,data:rsj8jzp/5UhXDXWKWeIwPTD1yilBfrX14OeOm31Fw4ahjTQf+kbjlqE+UcRBMnsI+1QPyZ6pnOQ=,iv:THzU6mI+1ea0VDgKLhbXeESnzlHR2Tpzu+sxjbyoP2M=,tag:8bhBLW4moG++HPCwZOZbow==,type:str]
    uptrace-headers: ENC[AES256_GCM,data:XvOYopYhRa/Hh9VD3qG7x8jvOIS3T5FF7Pzw7cWlM0Y57K0RjDe7MYDrbhpmcJWkUAuHvXKjggWnckhlWyQeWjEBFRg=,iv:bCAt6M1Sbtntqgdt565BPTgzlWvrV4j5cHzcJXwEzq8=,tag:ufEeWjnPNXcbUth/ZfK+Jw==,type:str]
    jwt-secret: ENC[AES256_GCM,data:clBGSjaN2dg4dQ69O8so47bRfuOyf1f+NIUWtSm4ROFLsIwXrtKeiojP+/g=,iv:dpT0diQdvZtrSSuNch8W0mWuzp6CGPgG6RdtvwTPexo=,tag:xdUiz026pZFpbavndkUQUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNjNFd1NtUEtpZWRnb3Zp
            ZktqSzNsSjNvVEtDdllRTDBmWnJycHhWdFdNCjBqdm93dGxQL1dNdWkrUjJYWHdr
            RG9aUEFhYzVNOS9WVmpWSnVVc0EydjgKLS0tIEZBTTk2bFdzbXYvREQ1c1pES3Vr
            QVZDTUlKcVNyb1hmMTlKdlRibHVBSTQK/B4kxwoJx7/7rSQlI31kq5jzEmRvk5r+
            GQbIgDaVRsvtq7AFlVHFlyLvWpfXrMkWp/R7UaHmrL6HMffI3SWsTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:O6TDRM3ytt3+NR6WwJmmEGmOLJ4zkDCFl9xuuPiklyyRTohOMphzk/QPXG/zGHZ/6bUE04nfBP9fHbuJFhGvAGBr5+brB/mEdD4UHdshLGDrgXROK18NUNhHYL/nq5BqTVEJe3I6AqNcSlqXiIG2Glur/chDVRc2F9v0M+3X9/Q=,iv:O4yX4wdUVYh/jFibchxYVLSkINzMH24AS3W/T3KyXvE=,tag:JMwZp/Oe5RDhoXYSvWBf9A==,type:str]
    version: 3.13.3
