apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: auth
type: Opaque
stringData:
    DEX_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:m9agiKAkoSP/CORdAkA2ndwBhNc=,iv:yCItJ7lPT/4wKauyNF8rOuEKP3JE47jhICPCOUGKIhY=,tag:PRRCHMuIn/iAKH4chXCMuw==,type:str]
    DEX_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:oCLIxuzfNRJ8ebAntteEFuPWPyJnmV0CoQfUf/Pz2fzQnHjlX8ED5w==,iv:BQd2NKELgvIHz14Rx78CZTVrL7jQ7krfk5ezyFn/SHs=,tag:PjZxq43CroZWE40fO49A5g==,type:str]
    DEX_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:NIdR3JeaXbxY3QMPoSBUs3oc2c0sj8BtQ33wfNcLjfE=,iv:cMbWgUihS/vkPF/ToNgTOTVjZcvY0ds5MltPkgCnZ74=,tag:iTXANdGMDz4U2iiupyuCxQ==,type:str]
    DEX_KUBERNETES_CLIENT_SECRET: ENC[AES256_GCM,data:GapDf7ckzoMpRtgteG2emi0S24piOI0h0gZitS8gUw0=,iv:29YOgwjoFtvn1aY62t7VXLdUwpqIR73rmEtWleiuQ4U=,tag:NkSIjvk4mheUFlPLKVXqtA==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINUdreFlrbUsvQ2NCZjlw
            LzNVMnpsdUZwYU9ybmpnYjVBMUluYkozNGhZClE0MkhPcnN3UUFxRUh2ZmZBQjdu
            TjYza2FMck9pZVVKU0w1am9vU0RNamMKLS0tIEl6OTFaNlZxOVVVZ0t2RGhZVjdC
            dUJDcHhvRFBDK0x3MnZjaFQ5Y3RweVEKcT1qsVWSfw5YWpX2wNnKZIXuMkYwFyj7
            E9o1B4iwvV5a8VY/wQPwA3BSG+rcbFhkqR7MSwquYjgfTQZhAaEiUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T20:44:04Z"
    mac: ENC[AES256_GCM,data:QJDEAnqcSLtNVqR4gKJFq3oBhcdK5RUwSwT5FQ1vkpOZ9MYXaNc4ws0+GynK6gWgNO+eyZekL21Pndvd9lAoR7rbKpjEUfI1kXYSRJvdGirGYy0TKKQKkKwshTmOxBZ01+3Pm7ESjFZg2DzU6stsN7yBwNMbxWCcFNso98AAhUE=,iv:WOm5iclyexZfc0p7u//T2f+ggWe32qS2DC6W5p54Ego=,tag:jh/NdZukQgg+/xvxRDgcmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
