apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: auth
type: Opaque
stringData:
    DEX_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:aSaaXmO11zVLh2R6BysI3LFhFMs=,iv:lMH0/r0DpRDeEUbx/1Vmhk7L+Df8gukFyzUwe2rVt9U=,tag:1pjqw+Gx3VGFSE5JcN0pBw==,type:str]
    DEX_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:klGnQEWYSY9fQSJHN4q6df0tAkdgMaAm6znTo1G8jCv2agbCA5ThqA==,iv:HbQl1OuSpECpiZSiHJ1CD67rM8DbhcSFzuVOK7kpMzQ=,tag:oslM4nuVCldPfPAdIxa4TA==,type:str]
    DEX_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:JpUlEyTCrJiSuT1RE9ReDK10buL/ZUMpHdaxUdDX66E=,iv:MzeymaKEdq+nmuaQE+md/dFunFVhDwobfwqum0NKfrE=,tag:YZGGHnD7Avauyf3n5AoRKA==,type:str]
    DEX_KUBERNETES_CLIENT_SECRET: ENC[AES256_GCM,data:ZEJw8EidcQe8WCMCtwGfixkErJLibaRQi4OznjbNmvA=,iv:iLxBhIxFhdG+KIlh1PqMyvhjxxoYEXuTQRLAGnjlauc=,tag:/SHZEutapDaMLPLE7gtZqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMk5aMU5zemNQYUNOT1Zq
            YS9UbCtDUVFadURxRGtDUHBRcEYzY1ZmcWdBCi9RS2lWc2tvaFVOazF2eWdjNzUx
            dkFMbm1vOHZ5cjJPR0gvdnpTZVFKMVkKLS0tIHRiUmZYUkRpc3I3N2pKd3JBaHZN
            NVUyMU5nT3dNWGZ2U2VvWEorMVFmaEEKnEz4IpmFApde2/zCH9deznCB+BtkdtUN
            DFdLKc+d28WHS34mP/2PyBn74apxeHskN0AGnc5/GCcbpIqmlcJ6Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:Zf5jzOn3DMyvJFnC7rJkvU0M2+cLqOKu7mg9Vr1FcJ6B6XjyyHHRtxHOguy/cIUT33MwcKPj7aaIl+g6M2vZKqEVupgN51xGupPv2vtXsnlvBG6qT9xuK3wy5KX4P+YL9NDaikdKIa2F7tIv/xBtq1uVFk9vdRU3w4eFN1gWX8k=,iv:/WbRuZg12hgAbEMmqax5D7NKjl9cT24DL6VKi4qcIbQ=,tag:sof4Nt2EgAsadpaDaAhE+Q==,type:str]
    version: 3.13.3
