apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - backend-dashboard.yaml
  - frontend-dashboard.yaml
  - backend-slo-rules.yaml
  - backend-alerts.yaml
