apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-latest-tag.yaml
  - disallow-privileged-containers.yaml
  - require-requests-limits.yaml
  - require-security-context.yaml
  - require-trusted-registries.yaml
