apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: develop
namePrefix: ""
labels:
  - pairs:
      environment: develop
    includeSelectors: true
    includeTemplates: true
resources:
  - ../base
  - image-policy.yaml
  - image-automation.yaml
  - hpa.yaml
  - pdb.yaml
  - patches/feature-flags.yaml
images:
  - name: ghcr.io/ldbl/backend
    newTag: develop-v0.0.3-95f6bc3-1772667218 # {"$imagepolicy": "develop:backend:tag"}
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: feature-flags
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: backend.develop.local
    target:
      kind: Ingress
      name: backend
