apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base
  - image-policy.yaml
  - image-automation.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: frontend
    newName: ${image_registry}/frontend
    newTag: production-v0.0.0-0c4cc88-1773188231 # {"$imagepolicy": "production:frontend:tag"}
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
