apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: develop
type: Opaque
stringData:
    uptrace-dsn: ENC[AES256_GCM,data:/lZGNhrh+nZo+3dlQ79tqDel63HQRm4BOs62Mhm62QurPx+SNS0osUzwjSKZRZOWLHfur/8Kwqs=,iv:8SL+u9VeYlS5SC/x3uFUw1qY5MQmrXflCYFpjOSL2pE=,tag:Kof+Gc7NvqHlH61+hYvClQ==,type:str]
    uptrace-headers: ENC[AES256_GCM,data:9jJ2QQsszUQlBXtlEqbMk721aIdQSNSpLwlsOVACfsHTRILsSmNeHHby9MIw+zVeyg7o6xnnSt1HVi+0yFNBTothbJc=,iv:1HpxmVi9wp5Bmyh5V6106OOhWAGUZZObQTIm5EJOAeM=,tag:a4O+kgXdD8huDA1MaKgnDw==,type:str]
    jwt-secret: ENC[AES256_GCM,data:jHewlVdQRbsHoDgYyiQaozN8K4DQ3t/mpgrdFDmEStY+DscKs+OJNJAYwOg=,iv:4UUfEO3LQjZQXdGcxZxNzS+KIgE39nMSR59/vrLOLm8=,tag:2QGbajAYiVWC0lPapbZ2Vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMEc0b2JObWFveGFqTU9Q
            ZFRNWFNUKzNwckt2NUJ6bWcwSXBkR2FZaVRzCkRXaEdCemNLN1B1dFVyZFJQVi9n
            Vm5FWkxGdkkrOXpqUWZGNk5rMTFyVDQKLS0tIGFSUFluUVdpcTBVVkEwYU1tYjli
            R0xQb0tkK0RDWFJmMGJLS3lrSnEraUkKdEtR7tAH1dKqZMyHc1bs5Zal1kOq7wrR
            6G8t6VS2uDjdLHYUC3aaydEIivaguaDntNMBZvRUZ1thw8P4ooKwOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:tMFWe3ySUQ7UPhIfTvm1+krN6r4ps2Vz9juxdRoYcVLNYfRDbkh5sRAcReS8uDpLspB0sdUlewtjO6qP0kBQYx+yBjL3JRwJXhCQYqX79k/e7JkDSojjK5DFNQK/hFhe9o4mv2r8zpoaOe5HI12pRb9FHeC3TKcSHkAGA4LOiS0=,iv:tZxTQ09XlkuPM7GAAUFgVDqWIHB7BYaK4NHU9FUfKJs=,tag:i0wr1HJNmPLGpOTeaQrCyA==,type:str]
    version: 3.13.3
