apiVersion: v1
kind: Secret
metadata:
    name: app-postgres-app
    namespace: develop
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:A/Z0,iv:Y05a3P624VLzUA2QBpdLaYHvVb/AW9JhEUnd7eP2sCU=,tag:IqYoiwFF7k+xyS8OKLYqoQ==,type:str]
    password: ENC[AES256_GCM,data:wSkLgWabyie2DvUHSdrek9GfujicdzFa0FAOHqH3nmA=,iv:TSlxi9FKAY5NwJLPz2+mYZWWx03xcGy7NJmZ86dAVMg=,tag:dUgDi9oxbHqQ1/c9IvXAAg==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabzIycVRCMnFMVlRyZ1c3
            Y2hmYjUvQS9iZmJqcnpwbUZVc1lXdFBGZUR3CmlqWEJralpURXFOc0NPc3RGOVJn
            VStYTDZtMXhVaURvZ05YTXAyWHNncEEKLS0tIGZBUG9OSTB5QmNLZ254TVFUK2g5
            YWtqS09FdEdSOTQrZ1ZFR2w2Nmhycm8KRIMJtQHQbNgAwAN4I/G7D0OR831zxw6E
            HFny4m9ZODtm4oPMYmLg7Gztt2jpb09eVmxAmUWx62oYW5Fl50ehCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:36:09Z"
    mac: ENC[AES256_GCM,data:fduhjMVG3of8yBCQyDJMn6FwuDQr4M04t0xvGA+5O2tJwc7T8dqgG37tfmxPkZ93XLkHsUspGNWBq7E5yb0Ertx/Fk6P8CR5PwndPYfTFzs7uOnMjmqggpKR2DJImyuud1nmos6y6AgPkmyc/XwI+EoR38XVSgaPDd4JAsllfig=,iv:NPb72P8ErSuXeTv9uPs/IADAU0cYcqt1Xwg8GKOQcWE=,tag:5VivviiRe5zI2cm/USiATw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
