apiVersion: v1
kind: Secret
metadata:
    name: app-postgres-app
    namespace: develop
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nYRH,iv:TeKLLXnQU/O7cCEU8u3OyUSauewodTYFKz9C4vefut0=,tag:SJKKR1iGs9lKnT3w/LkhzA==,type:str]
    password: ENC[AES256_GCM,data:et5IoFm4ysBWsAwOKLoxOhLrBoFF3i2zyrOz7y1IKBU=,iv:YIR36hiC0mSqwk8rGd29Uazg+bmztaJ18ziYyQRFgPY=,tag:+pKnf8DGF4u+mbOLU4pFQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbW5oclZWL0xDSEZxRTky
            MEtLeFNZUFZ0eVdOYmc1aXVpRWd2cnUvUmhNCldhdHc1S3NYb296NWQzMGR2WWJ1
            aTIxaSt5dWpKUFZtSUowZGwvamJRbncKLS0tIHUvVThzU0NqWUwxMXNacVFmcFgv
            MUdLNi9RaFpJaFpieW5FZUl4bm9ycjAK+cvoXBPCe0+rt7vOwF8/OwNte2Qg3k2J
            FoyR3WCunx1UAogVckUiouZ5hT+NFFST5uZxt8CmhIeYHeByP4Aoyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:+/d0IfSPmlOEIccYla6jl7ANfkU6SnXKPVCeHnDELsQg9D0I40d5V9rFNbK9wfMaROU56D83TYrNPUlC3PGj9rGSRA/+ARk3s62f+k/5j5fsdviFPWv4JJ1qk/+cw6a1Wt1R83U8HMe0nV7JpIzXjUZodaa4u7eOQ+f6RW+pCsM=,iv:wVIr12g5xjrqpbLlLV0S/ffUH1y6a0MxpLIpsH50Rc8=,tag:c0RuOl0cul+z6IC5mysM3g==,type:str]
    version: 3.13.3
