apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
namePrefix: ""
labels:
  - pairs:
      environment: staging
    includeSelectors: true
    includeTemplates: true
resources:
  - ../base
  - image-policy.yaml
  - image-automation.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: backend
    newName: ${image_registry}/backend
    newTag: staging-v0.0.0-66c44a2-1773188533 # {"$imagepolicy": "staging:backend:tag"}
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: backend
