---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: frontend
  namespace: staging
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-image-automation
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-image-automation@users.noreply.github.com
        name: Flux Image Automation
      messageTemplate: |
        Update staging frontend image

        [ci skip]
    push:
      branch: main
  update:
    path: ./flux/apps/frontend/overlays/staging
    strategy: Setters
