apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:TcDn1S9DCtHdYoCyM2YtRuBOwxnsr2soc9Shko960qcbtFFSxZj6YU0r12eQZ1paj2+rnak=,iv:Incpui8smNEeY/Twz25F+z+/RYWlOZeh8jFW4mL3w/Y=,tag:A8eoS5/GXGaODhf0HryS5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnckJhRUVYZyswU3d4NkVJ
            TjdGTzhyNlMzVlY1MzQ0dldhSG93NFlMczBFCnZFcldFTE1wVi9NNEtPUW1acmpD
            bGh6ZTN1M2VPVk90OGUwTHNhWTJaLzQKLS0tIDV3ZHlQUnRoWTd4Q01wTEFUbEd1
            Wk1vYnRnQ1NMLzYzZHdCYXdOejlpRVEKThBMN340YJkPSLDQZ6+yFfzB9Hrmv94b
            FG4OxQjunifaQA2rljqYKb/T9eY/a5PWS+X//rxTMHzeZi6Ll3+T+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T17:08:03Z"
    mac: ENC[AES256_GCM,data:jzv8t2HSM1/ZnMMwrTD/anXtmep9J2dYvop9+fuT+AiHug3yCMf85s5xpx7dOkMeGFlKwvzp3VE4U5xTUWe77r5IedoZ54uNvUQaEUASecezKEE9qRttQt4Lcdoiixz9WpQ2lIs7WsijCqRy3HXEzIs3TwgGWAvg+wnFpiyujq8=,iv:cKLSV7zABwosWdYmZuTiZVSkoVTl+PvJkxoqOFIuWqM=,tag:SgemtZDD6sk7luKEUR7mRQ==,type:str]
    version: 3.13.3
