apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:rBLp5Y+Xa8AB7M1JK+sW2NpLyJI9EVUCWT2+7BVoOfQZZoWNviEI1Uknzlq004r+yR+IlKA=,iv:MXo5b1qaVLHYzhLSz64WirrfCkOwEqSqfwFW3sHE5hU=,tag:ww0HvO+aeBmwjCQUJuL74A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSlZZaWU0QnJ1WUlORm9D
            SEtWWFNiMTMxSkFpL1FrL3dyRExZb1Q2cEVZCmZ3SjhxN0tRWTJDSDFsTmtBb1l3
            TVNieUZNenViUFYwSklBNHBGaU0wL00KLS0tIDMxUUlhTnIzVk4rdEUzTmNMcGh2
            Vitub1JCcjZwZ1ZMUTdpN0VObTJ1SmsKftw22HIt1+CZAHUwAJj9A3Hte1FXNe4e
            7dMd5I51gX9rb+FCCmiZun4TFZlbKkiq0LJ6hd1PsuelnEJEEtD0UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:Zwfqa9rqQXFYy+aETt9BaM6VVvk1n9XK8qpa9cF7QCA6d4FT4ed6ZINY4UnP+Mpo4Pirw3S0LQ70DkMP3xY4XpRBrYD74LRXDXxYKJ/eopF9PrTKJS5cnfVP9m2anDz3K0PIfa8lOnsYQFVnj0eQ7sxw/tF+DI3YYt5kMjZ3g1g=,iv:L0M5NqzC11Otecf3TR4brRorvFoKXxA5tflr+Ni7QOg=,tag:Q9NLS3OvZZ37wFgkNPvpaQ==,type:str]
    version: 3.13.3
