apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:V2TkDGI3LlW496p9xg+GbDYcrGg+vpiDQ463tTscZ4jHUsGQkwqEQTPXD1QO8g03NSsF1k8=,iv:NHKuakm3EWXTJaPOD63i+wXO7SX5OPEBYpe4Kj9xrnw=,tag:ue3Bhjn5C28zvMrkCkYPhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByekFmUFZ0MTJYZVNGcXlj
            WlRkblRPSXhvbjRNSXk2OC9EZ2VNb3JPZERzCm9jaW9PZC9zMHJJb1pEOEtYK2pk
            Mm9OcU9tNHBpN2NXYjhVT3BjSDA5cWMKLS0tIHhkRWZZbGNPYXMwWGhESStYVUlQ
            OEhGbEhmejkyb1dUM0JyTGFHb3J0UmcKjTekXZL7vNTwhp9loPUhH4MnxpgTeITL
            TWqcEKr92Sd0krCpXAiPAsw9RSoCWVhNK1SHsOE+lXWrnQBGzkkzlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T16:12:48Z"
    mac: ENC[AES256_GCM,data:hYxisez3wjVkK2gahsujoEMD4okL6lSCQcVGCP+dxvSJ+18fKF6It682DMl+TIRje2f+r2Xvk5+9VfcgrrgaAxPKLj7Mlh8sWTxeMahN/RiOqE42FkIx+PkCuM1TyvTLNvuxLU2AK9ElBVOCWwh/GsqrXihJ3u+JUDslle83fFs=,iv:IwbztfmiU7PLWiiSRojk2WaO7X7l1sPtup0bJWlRFYU=,tag:JICZoyA6awydsGEu6/Ta0Q==,type:str]
    version: 3.13.3
