apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: staging
type: Opaque
stringData:
    uptrace-dsn: ENC[AES256_GCM,data:0nhi42o7gY9g4C39lTrTUaKlt9nPAK72sgoQLKRAJhZVdR0pwVAezZ7X4GqeCDBd9TQJtJcw1JQ=,iv:WYw5ek3hOFf8ET8WOMDEco6NR5+mNGfL10oBDhUw0eY=,tag:LvDcbrg4xkXrtB4e97ZEvw==,type:str]
    uptrace-headers: ENC[AES256_GCM,data:0cyfa59c9qYIGHkj+dzSU/Tm9CoiYJMTK+qMv9v6IEh+fSKx/r+DBSHPI5yJ3d8MX6NfQH6aOol2ahbfXXT+H/fP6rY=,iv:UQDL25zkieriEH1uS956p9s+cMuFnyuzthtZt0Cwhes=,tag:zHGiieu9tIh6pdW2Om8AfQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:P+qvg1YgCHGLLiF6k6AE9yFfHA+/2fdgLKbOXUx/0QaBqba9yJ1up6K6Z/Y=,iv:VBJMgKAdmRtA7Ejh3WlxACSGF24H/KnaVIcnvizA/nA=,tag:gjIDajZgKH2c4qEm44B+lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSmowNnVTWS9CMDY2VGc3
            MW4weElSZEF5RlBJMjJmZEc5STdwMnJDK1M0CmliU0hFT0VRQzhydURZaWFEZ1hX
            dWRKeWlrSC9nUHByMCtHdDFxQlR6MWcKLS0tIGF1Snl3cklIczhJSldabElXMnRs
            SjIwd2xUbjI0M3d3djFuWW80dHhwd0kK0TSlDl5LwVsVCpR7TOTfRpdE11b0mFey
            NFxBNHp8RJdcktamdnVdK8C699sjmz42uJ7rN8M5gW1FK9ScIHLTIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:E1Vps9EbcAJaw5DweS6N1XvbVtF7yTHJplTqyrZKjwYvY3g7JbkUSNArJMFteRNbkvzLiGDJfsf+t72Or9AzbC00WTPIYJfRIWiYJyY5sn+AJrlF0cNvl2FRYfms/961CuATt2MSqXjmeEsVq3GyRIW0uqTm8zdCGFQ2Mmu/sFg=,iv:P/ffzG6ABLgWxBAt2e6DzeQ5l/QuDkjgsa22UW+i9ys=,tag:tqgSSjtCeEFOzZiViRuZlw==,type:str]
    version: 3.13.3
