apiVersion: v1
kind: Secret
metadata:
    name: app-postgres-app
    namespace: staging
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1F1+,iv:E04qLleV3pF54L9478wF3zwo95XyQvnEqqYulsgYKvM=,tag:EdHe22BiU++YTCD4Y0apmQ==,type:str]
    password: ENC[AES256_GCM,data:HZ2FnH491sk5pEHRo9B8xBeSm4kWDPNuLJ1Wh1L888w=,iv:zMF3u2djmfikptwZSHnLkI16uaaGd3CDB75PdPuOnPQ=,tag:zmKF+GTctD4FUzorCPnoSg==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdVRYbm9wVlpMMkg5NnZy
            bFBWQXhEdUw2VWVCOEF5Yk5qY2FvNnY2ZHhRCmwxU09TL29IWTk2TjQyTTAvUTRX
            cjdOOFYwbnZvbFZKVDNmU2ZFRXhOUGsKLS0tIE5RN2VBUDl4VkhkNGt5RERVRTJC
            dThaaVVDUXg1emhVZ1YrVTg3cUd1TzQK+hUHRZvxcUJKaS9CrcXKaCOLsqWKAY3v
            kVHGq57HkuXLcR2dQ9adxyRazoOAqrs8QeEVR1Y1IVDRwx2oeNEJCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:14:52Z"
    mac: ENC[AES256_GCM,data:xXCyU0o63UpqGU7BLYZVvpOjMiVMe5FNAQl0ReV/RyWW1Cmyg4OogUZkYp/qzZOTLLsBMn0jP9kKB0tMXpmHIz0o1eHgEPoa3omnm8Cz7ebe1KlBay8JOvdaqJoLNrt/JpPz57QmSleHKfANAx8HCUYLri5nrN6tRfWh2oQ0tk8=,iv:Q1u+hGx6xjAWnmv7dBEmgW161TldNSNkaJMpWzKuaSM=,tag:4z3oxRqHcq7gJrriPEAhdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
