apiVersion: v1
kind: Secret
metadata:
    name: app-postgres-app
    namespace: staging
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mgmM,iv:z/POkEiQnt0dihkRyRnlp3I+jCPN6voYJt53YJWzvhw=,tag:AodlYirIlKLBi6Fw6hhyug==,type:str]
    password: ENC[AES256_GCM,data:y5oppor2wX9GgFGMGET6Y7PImce7p+cbdymj4ypeF/U=,iv:8+2Y8yffBnZx3ZgBBFOE7WTI6z1OWG9UGYjZtD53sOw=,tag:Rjjoi9jLPdbaURHGvund1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUWlFcFRhVjhacWRadmpj
            ZzIyQ0hiNU40VDE5RVlwZ2pCSUtiWVpXRlJBCmRrZ0R3SmV0WC9MOWxGbEFRQk1j
            TGdzSzVoNlZ2eWlOaFRaUkVObDRWelkKLS0tIEVlNTZ2WjNyTzMvZUpjUVpLTlo2
            TjVDTkM1QUdrOFY1MTU0emlMQXhvdUEKNrYG4jM1gEQsKmReJ3u+IGsSw+91YIuk
            Y+uQFZvfAiftIrjB0cA/8TGJxWnS4aAa8s0lpp7f1nk0tzCjrna1UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:s1CgVCw2h4S32VnHMTDjDnsFwFf/0YVa0RVHaMfkW/l9bfMdWcD4fxR30P/nDplQI4AiCiGBgUwNIXdO+vUXYRn6pzGbq3dRqBE2ikDMEC92n8QB7+G+VJSyZtW4ci7Llv3zFx5XoLm2HSi1eewm2mGt0RymPpC3jjERTPCjaBw=,iv:3RnZi+1NtXK6Jy9gc3T0MsbGjvQyui69h59nqD+GT7o=,tag:yXXuy3WVjOYuyzbFpGNMjA==,type:str]
    version: 3.13.3
