apiVersion: v1
kind: Secret
metadata:
    name: uptrace-secrets
    namespace: observability
data:
    dsn: ENC[AES256_GCM,data:Ww7n5dKvEDKaxrnl4lNWVoZH81JZVEWTRmB/0qDavNA0ca7GVRXdUsfoLNWrwf/C3r2FARpqhAHVc3MLV3PvUR+xznjBZABQR3exaw==,iv:OFEyTpHyKMjjrKgpVMrfTSqumMn0V3Aq8JEBvJk+B3E=,tag:QRiLwvu3fKFaPvdkDMw/6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2JTYkd2N09WY1Y3a2dm
            aWJqWjlxdXVNVkJuQWpwOXRNUFZ5ZDV0WXpZCm9oNFV3K2hOSzR5OE51RGJ2dzRz
            UncyYWFLTERpTmZDZ21xUlBKaitGbGcKLS0tIEJxamY2cHJnbUdubzFXc1pvN1lm
            ZDFFenYzWDd2QnZHbE1ZTDR5cXlTbzgKvQ7YvEJVAvsI2Gn5lO2GBVFOvZpaz/Mb
            tYUls6zHDQbycNOGUoopHolPJ2H+5rNjH3v4oNs0c9bVfEEP/JcGWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:25:11Z"
    mac: ENC[AES256_GCM,data:fF3zcC8MF+1IqFTec0+AXL2uwbbIy/Rmuo8SaONKTeNWOl/hrUeYc+vHVs9b5OzGCfsK9ROpBUsSCORF1rr8Jo4szVX1mNsVz91jr5cNl1SemG8zvGWAsMOO+mGr3vfdhaOefrl8JQyQQfvreAvwrTAgSCFIFct5AYbpsly/gb0=,iv:pE1ezI7I+7MVLPK9WnKMI1m4t3s2lta2I/eXi16+Zs8=,tag:TNSbFQik3Rk5BNDaU8+FSA==,type:str]
    version: 3.13.3
