apiVersion: v1
kind: Secret
metadata:
    name: uptrace-secrets
    namespace: observability
data:
    dsn: ENC[AES256_GCM,data:CxAJKg/HhBTKewojbqmljoeTi0ye3xrZ/pcOBYUZnLHAYqe8gVz/dctjZHMWFD7KOU76LDX4beyhWKxlLmNq+7aYXz6XTiV+eecYDA==,iv:masvV3p0miEhjHxqq6Ls0XFQ/GvHYXwVIJAQEd2xrLw=,tag:9gEYwoXV85rc1AOwjs/5gg==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RVNqRmQ1YWJoWEp1S3kr
            UUZ0Qi9pV0pxTHdqNzVXV2MzeUpPQU5EUWlVCjFSaDI1WW1OcmQvUVZRRHNqUVNj
            VTBOQVRnYWp2VTl6VjR3blNLaGYvY0kKLS0tIERQUC9vcTVnQVY1bnVJVTAxM3Jw
            N0sycTRhb3p6WFRBTTRCUy9WcTc0cEkKMW2Re0Prdia+7BKO9Kmz9NA1fA5kVfOC
            CHO7XCXeOsbmhc1e8P4cuO+9bG1RuqvZMUREiS4KcgEtOSfnbGhTDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T20:25:02Z"
    mac: ENC[AES256_GCM,data:YtoewuO2iSSjHN0ZDObFYUjSsKqqEHAahJZBk5NTg6aaMt7TgAgXQLdJt6LdmOwmD8VmTFqPp9R1ir8pONKx7/KCutEJxghWM/flQbcEPAJOwKeTn7xejkxYcB9dL5ts4LoeDLp8N5nyoFQgRAxBiOpyPFri+yHAu4JzP1G2+vU=,iv:4H/GzX7Yeskiw0643Z9FTUBQg7JgxjZ/dfAHanFR8VE=,tag:andvC/kkzP6M00mzHgXsVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
